### ISSUE TITLE
Exclamation marks are not parsed correctly 

### ISSUE THREAD

**Issue by obahareth** [yakaz/yamerl#26]
Hey, I'm using trying to parse YAML in Elixir using this code:

```elixir
:yamerl_constr.file("./data.yml")
```

and I get this error: 

```elixir
** (throw) {:yamerl_exception, [{:yamerl_parsing_error, :error, 'Tag "!textFormat" unrecognized by any module', 5, 19, :unrecognized_node, {:yamerl_tag, 5, 19, '!textFormat'}, []}]}
```

I've tried parsing the same yaml using Ruby's yaml gem and it didn't have any issues.

The YAML looks like this:

```yaml
IDE:
  editor:
    themes:
      base16-zenburn:
        built-in: !textFormat
          color: "#dc8cc3"
          background: "#3f3f3f"
          italic: false
        char: !textFormat
          color: "#5f7f5f"
          background: "#3f3f3f"
          italic: false
        class: !textFormat
          color: "#e0cf9f"
          background: "#3f3f3f"
          italic: false
        comment: !textFormat
          color: "#4f4f4f"
          background: "#3f3f3f"
          italic: false
        currentLine: !textFormat
          color: "#dcdccc"
          background: "#4f4f4f"
          italic: false
        env-var: !textFormat
          color: "#dca3a3"
          background: "#3f3f3f"
          italic: false
        evaluatedCode: !textFormat
          color: "#dcdccc"
          background: "#4f4f4f"
          italic: false
        keyword: !textFormat
          color: "#dc8cc3"
          background: "#3f3f3f"
          bold: true
          italic: false
        lineNumbers: !textFormat
          color: "#4f4f4f"
          background: "#3f3f3f"
          italic: false
        matchingBrackets: !textFormat
          color: "#dcdccc"
          background: "#606060"
          bold: true
          italic: false
        mismatchedBrackets: !textFormat
          color: "#dcdccc"
          background: "#dc8cc3"
          italic: false
        number: !textFormat
          color: "#dfaf8f"
          background: "#3f3f3f"
          italic: false
        postwindowemphasis: !textFormat
          color: "#dcdccc"
          background: "#3f3f3f"
          bold: true
          italic: false
        postwindowerror: !textFormat
          color: "#dca3a3"
          background: "#3f3f3f"
          italic: false
        postwindowsuccess: !textFormat
          color: "#5f7f5f"
          background: "#3f3f3f"
          italic: false
        postwindowtext: !textFormat
          color: "#dcdccc"
          background: "#3f3f3f"
          italic: false
        postwindowwarning: !textFormat
          color: "#dfaf8f"
          background: "#3f3f3f"
          italic: false
        primitive: !textFormat
          color: "#e0cf9f"
          background: "#3f3f3f"
          italic: false
        searchResult: !textFormat
          color: "#dcdccc"
          background: "#404040"
          italic: false
        selection: !textFormat
          color: "#dcdccc"
          background: "#606060"
          italic: false
        string: !textFormat
          color: "#5f7f5f"
          background: "#3f3f3f"
          italic: false
        symbol: !textFormat
          color: "#7cb8bb"
          background: "#3f3f3f"
          italic: false
        text: !textFormat
          color: "#dcdccc"
          background: "#3f3f3f"
          italic: false
        whitespace: !textFormat
          color: "#606060"
          background: "#3f3f3f"
          italic: false
```
