### ISSUE TITLE
Upper limit on entries

### ISSUE THREAD

**Issue by DewayneG** [yakaz/yamerl#31]
There seems to be an upper limit of the number of entries in a list.  Using this example
```
%YAML 1.2
role:
    ownership:
       root: /var/log/bc var/log/bd
       root: /var/log/bc1 var/log/bd
       root: /var/log/bc2 var/log/bd
       root: /var/log/bc3 var/log/bd
       root: /var/log/bc4 var/log/bd
       root: /var/log/bc5 var/log/bd
       root: /var/log/bc6 var/log/bd
       root: /var/log/bc7 var/log/bd
       root: /var/log/bc8 var/log/bd
       root: /var/log/bc9 var/log/bd
       root: /var/log/bc0 var/log/bd
       root: /var/log/bc11 var/log/bd
       root: /var/log/bc12 var/log/bd
       root: /var/log/bc13 var/log/bd
       root: /var/log/bc14 var/log/bd
       root: /var/log/bc15 var/log/bd
       root: /var/log/bc16 var/log/bd
       root: /var/log/bc17 var/log/bd
       roota: /var/log/bc18 var/log/bd
       rootb: /var/log/bc19 var/log/bd
```
results in 
```
[[{"role",
   [{"ownership",
     [{"root","/var/log/bc var/log/bd"},
      {"root","/var/log/bc1 var/log/bd"},
      {"root","/var/log/bc2 var/log/bd"},
      {"root","/var/log/bc3 var/log/bd"},
      {"root","/var/log/bc4 var/log/bd"},
      {"root","/var/log/bc5 var/log/bd"},
      {"root","/var/log/bc6 var/log/bd"},
      {"root","/var/log/bc7 var/log/bd"},
      {"root","/var/log/bc8 var/log/bd"},
      {"root","/var/log/bc9 var/log/bd"},
      {"root","/var/log/bc0 var/log/bd"},
      {"root","/var/log/bc11 var/log/bd"},
      {"root","/var/log/bc12 var/log/bd"},
      {"root","/var/log/bc13 var/log/bd"},
      {"root","/var/log/bc14 var/log/bd"},
      {"root","/var/log/bc15 var/log/bd"},
      {"root","/var/log/bc16 var/log/bd"},
      {"root","/var/log/bc17 var/log/bd"},
      {"roota","/var/log/bc18 var/log/bd"},
      {"rootb",[...]}]}]}]]

Removing just one entry from the above yaml file results in the correct production of the erl file.  This is a trivial example.   The real issue arose during the development of quite complex yaml files, which resulted in multiple ellipses occurring.
